/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCupoesRouteImport } from './routes/admin.cupoes'
import { Route as AdminLojasRouteImport } from './routes/admin.lojas'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminUtilizadoresRouteImport } from './routes/admin.utilizadores'
import { Route as CupoesIndexRouteImport } from './routes/cupoes.index'
import { Route as LojasIndexRouteImport } from './routes/lojas.index'
import { Route as LojasSlugRouteImport } from './routes/lojas.$slug'
import { Route as OfertasIndexRouteImport } from './routes/ofertas.index'
import { Route as OfertasSlugRouteImport } from './routes/ofertas.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCupoesRoute = AdminCupoesRouteImport.update({
  id: '/admin/cupoes',
  path: '/admin/cupoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLojasRoute = AdminLojasRouteImport.update({
  id: '/admin/lojas',
  path: '/admin/lojas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtilizadoresRoute = AdminUtilizadoresRouteImport.update({
  id: '/admin/utilizadores',
  path: '/admin/utilizadores',
  getParentRoute: () => rootRouteImport,
} as any)
const CupoesIndexRoute = CupoesIndexRouteImport.update({
  id: '/cupoes/',
  path: '/cupoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasIndexRoute = LojasIndexRouteImport.update({
  id: '/lojas/',
  path: '/lojas/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasSlugRoute = LojasSlugRouteImport.update({
  id: '/lojas/$slug',
  path: '/lojas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasIndexRoute = OfertasIndexRouteImport.update({
  id: '/ofertas/',
  path: '/ofertas/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasSlugRoute = OfertasSlugRouteImport.update({
  id: '/ofertas/$slug',
  path: '/ofertas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/conta': typeof ContaRoute
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/ferramentas': typeof FerramentasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/cupoes': typeof AdminCupoesRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/lojas/$slug': typeof LojasSlugRoute
  '/ofertas/$slug': typeof OfertasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cupoes/': typeof CupoesIndexRoute
  '/lojas/': typeof LojasIndexRoute
  '/ofertas/': typeof OfertasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/conta': typeof ContaRoute
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/ferramentas': typeof FerramentasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/cupoes': typeof AdminCupoesRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/lojas/$slug': typeof LojasSlugRoute
  '/ofertas/$slug': typeof OfertasSlugRoute
  '/admin': typeof AdminIndexRoute
  '/cupoes': typeof CupoesIndexRoute
  '/lojas': typeof LojasIndexRoute
  '/ofertas': typeof OfertasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/conta': typeof ContaRoute
  '/contacto': typeof ContactoRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/ferramentas': typeof FerramentasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/cupoes': typeof AdminCupoesRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/lojas/$slug': typeof LojasSlugRoute
  '/ofertas/$slug': typeof OfertasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cupoes/': typeof CupoesIndexRoute
  '/lojas/': typeof LojasIndexRoute
  '/ofertas/': typeof OfertasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/conta'
    | '/contacto'
    | '/entrar'
    | '/favoritos'
    | '/ferramentas'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/admin/cupoes'
    | '/admin/lojas'
    | '/admin/produtos'
    | '/admin/utilizadores'
    | '/lojas/$slug'
    | '/ofertas/$slug'
    | '/admin/'
    | '/cupoes/'
    | '/lojas/'
    | '/ofertas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/conta'
    | '/contacto'
    | '/entrar'
    | '/favoritos'
    | '/ferramentas'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/admin/cupoes'
    | '/admin/lojas'
    | '/admin/produtos'
    | '/admin/utilizadores'
    | '/lojas/$slug'
    | '/ofertas/$slug'
    | '/admin'
    | '/cupoes'
    | '/lojas'
    | '/ofertas'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/conta'
    | '/contacto'
    | '/entrar'
    | '/favoritos'
    | '/ferramentas'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/admin/cupoes'
    | '/admin/lojas'
    | '/admin/produtos'
    | '/admin/utilizadores'
    | '/lojas/$slug'
    | '/ofertas/$slug'
    | '/admin/'
    | '/cupoes/'
    | '/lojas/'
    | '/ofertas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  ContaRoute: typeof ContaRoute
  ContactoRoute: typeof ContactoRoute
  EntrarRoute: typeof EntrarRoute
  FavoritosRoute: typeof FavoritosRoute
  FerramentasRoute: typeof FerramentasRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  AdminCupoesRoute: typeof AdminCupoesRoute
  AdminLojasRoute: typeof AdminLojasRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminUtilizadoresRoute: typeof AdminUtilizadoresRoute
  LojasSlugRoute: typeof LojasSlugRoute
  OfertasSlugRoute: typeof OfertasSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CupoesIndexRoute: typeof CupoesIndexRoute
  LojasIndexRoute: typeof LojasIndexRoute
  OfertasIndexRoute: typeof OfertasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cupoes': {
      id: '/admin/cupoes'
      path: '/admin/cupoes'
      fullPath: '/admin/cupoes'
      preLoaderRoute: typeof AdminCupoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lojas': {
      id: '/admin/lojas'
      path: '/admin/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AdminLojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/utilizadores': {
      id: '/admin/utilizadores'
      path: '/admin/utilizadores'
      fullPath: '/admin/utilizadores'
      preLoaderRoute: typeof AdminUtilizadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupoes/': {
      id: '/cupoes/'
      path: '/cupoes'
      fullPath: '/cupoes/'
      preLoaderRoute: typeof CupoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas/': {
      id: '/lojas/'
      path: '/lojas'
      fullPath: '/lojas/'
      preLoaderRoute: typeof LojasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas/$slug': {
      id: '/lojas/$slug'
      path: '/lojas/$slug'
      fullPath: '/lojas/$slug'
      preLoaderRoute: typeof LojasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas/': {
      id: '/ofertas/'
      path: '/ofertas'
      fullPath: '/ofertas/'
      preLoaderRoute: typeof OfertasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas/$slug': {
      id: '/ofertas/$slug'
      path: '/ofertas/$slug'
      fullPath: '/ofertas/$slug'
      preLoaderRoute: typeof OfertasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  ContaRoute: ContaRoute,
  ContactoRoute: ContactoRoute,
  EntrarRoute: EntrarRoute,
  FavoritosRoute: FavoritosRoute,
  FerramentasRoute: FerramentasRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  AdminCupoesRoute: AdminCupoesRoute,
  AdminLojasRoute: AdminLojasRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminUtilizadoresRoute: AdminUtilizadoresRoute,
  LojasSlugRoute: LojasSlugRoute,
  OfertasSlugRoute: OfertasSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  CupoesIndexRoute: CupoesIndexRoute,
  LojasIndexRoute: LojasIndexRoute,
  OfertasIndexRoute: OfertasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
